import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main tutorial/docs sidebar
  tutorialSidebar: [
    'intro',
    {
      type: 'category', 
      label: 'Races',
      items: [{type: 'autogenerated', dirName: 'races'}],
    },
    {
      type: 'category',
      label: 'Classes', 
      items: [{type: 'autogenerated', dirName: 'classes'}],
    },
    {
      type: 'category',
      label: 'Spells',
      items: [{type: 'autogenerated', dirName: 'spells'}],
    },
    {
      type: 'category',
      label: 'Equipment',
      items: [{type: 'autogenerated', dirName: 'equipment'}],
    },
    {
      type: 'category',
      label: 'House Rules',
      items: [{type: 'autogenerated', dirName: 'house-rules'}],
    },
  ],

  // Dedicated sidebars for navbar sections
  bestiarySidebar: [{type: 'autogenerated', dirName: 'bestiary'}],
  spellsSidebar: [{type: 'autogenerated', dirName: 'spells'}],
  regionsSidebar: [{type: 'autogenerated', dirName: 'regions'}],
  deitiesSidebar: [{type: 'autogenerated', dirName: 'deities'}],
};

export default sidebars;
